[mongo]
connection_string = "mongodb+srv://marcomoser:StFP1K9BdJ27oIqm@cluster0.qbihfmk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# --- Credenziali per il Cookie ---
[cookie]
expiry_days = 30
key = "ce_festa_auth_key_2025"
name = "ce_festa_cookie"

# --- Credenziali Utenti con Password Hashate ---
[credentials.usernames]

[credentials.usernames.admin]
email = "M"
name = "Admin User"
password = "$2b$12$uzz6F3gpqgb4E2C22SETq.fG9JK71Qwh5Wuyy9rR9vEYL3wRoc1ZW" # <-- USA L'HASH
roles = ["admin", "editor", "viewer"]

[credentials.usernames.mmoser]
email = "M"
name = "Marco Moser"
password = "$2b$12$69Q5JdaZ6cSFCHwGfdk7VOcLHfXBuj02kzhIiQLOgkbikdJ0z2rAe" # <-- USA L'HASH
roles = ["editor", "viewer"]

[credentials.usernames.ggiuliani]
email = "giancarlo-giuliani@virgilio.it"
name = "Giancarlo Giuliani"
password = "$2b$12$69Q5JdaZ6cSFCHwGfdk7VOcLHfXBuj02kzhIiQLOgkbikdJ0z2rAe" # <-- USA L'HASH
roles = ["editor", "viewer"]

[credentials.usernames.cgiuliani]
email = "giancarlo-giuliani@virgilio.it"
name = "Chiara Giuliani"
password = "$2b$12$69Q5JdaZ6cSFCHwGfdk7VOcLHfXBuj02kzhIiQLOgkbikdJ0z2rAe" # <-- USA L'HASH
roles = ["editor", "viewer"]

[credentials.usernames.user]
email = "XXXXXXXXXXXX"
name = "User"
password = "$2b$12$69Q5JdaZ6cSFCHwGfdk7VOcLHfXBuj02kzhIiQLOgkbikdJ0z2rAe" # <-- USA L'HASH
roles = ["viewer"]